# Generated by Django 3.2.4 on 2021-06-08 09:16

from django.db import migrations, models
import froala_editor.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='BlogDetail',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('content', froala_editor.fields.FroalaField()),
                ('image', models.ImageField(upload_to='blogs_image')),
                ('slug', models.SlugField(blank=True, max_length=1000, null=True)),
            ],
        ),
    ]
