# Generated by Django 3.2.4 on 2021-06-08 11:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_alter_blogdetail_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='blogdetail',
            name='into',
            field=models.TextField(blank=True, null=True),
        ),
    ]
