# Generated by Django 3.2.4 on 2021-06-09 02:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0003_blogdetail_into'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blogdetail',
            name='image',
            field=models.ImageField(upload_to='images'),
        ),
    ]
