# Generated by Django 3.2.4 on 2021-06-09 02:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0004_alter_blogdetail_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blogdetail',
            name='image',
            field=models.ImageField(upload_to='blog'),
        ),
    ]
